# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7c5521de3d136f865c9546447000f5b6966cb36fc275b7b774bc0686972fd73ae87085e39e6cf3a6b665dd0d3132c53b5afe8e26a1282a7662d86ff1852ffde

test:
  secret_key_base: d87a831a6fbafba97f180d5da9628b2870a61766a6bab65030ee6ba1e6202406fa3fadb6b91f80adc03d1035db71052850aa5b1f5dab73098df9a73e7d733481

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
